# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('mail', models.EmailField(max_length=254)),
                ('nit', models.IntegerField(unique=True)),
                ('domicilio', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
