# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.IntegerField(max_length=15),
        ),
    ]
