# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20170118_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.IntegerField(),
        ),
    ]
