# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulas',
            new_name='Factura',
        ),
    ]
