# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-18 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_auto_20170118_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='opservacion',
            new_name='observacion',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='opservacion1',
            new_name='observacion1',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='opservacion2',
            new_name='observacion2',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='opservacion3',
            new_name='observacion3',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='opservacion4',
            new_name='observacion4',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='opservacion5',
            new_name='observacion5',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='opservacion6',
            new_name='observacion6',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='opservacion7',
            new_name='observacion7',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='opservacion8',
            new_name='observacion8',
        ),
    ]
